
# Site settings
title: Hole Finisher

# Build settings
include:
  - _pages/

exclude:
  - tailwind.config.js
  - postcss.config.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - yarn.lock
  - yarn-error.log
  - .jekyll-cache/
